Add export to allow external scripts to get killer data
Qbox-project/qbx_medical pull request #97
Opened 2024-07-22 02:52 UTC by JHansen2000

## Description

Add export to allow external scripts to get killer data

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-07-22 02:57 UTC, JHansen2000 commented
Sorry for the messy commits, I had some old code I was playing around with that was fixed by someone else's changes and I forgot to remove that old code prior to opening this PR.

2024-07-22 03:27 UTC, Manason requested changes
Would this be better as an event instead?

2024-07-22 03:30 UTC, mafewtm commented
What is the usecase for this as well?

2024-07-22 13:19 UTC, JHansen2000 commented
This is helpful for developers to be able to retrieve the killer's data for other scripts (i.e. a deathscreen that displays killer name and how they killed you). Without this export, external scripts must listen to the native CEventNetworkEntityDamage and parse it on their own, which is very inefficient since Qbox is doing this already.

I think this is better as an export, rather than an event, but am definitely open to discussion if you think an event would be better. What is the benefit of using an event over an export for this?

2024-07-22 15:34 UTC, JHansen2000 commented
> > This is helpful for developers to be able to retrieve the killer's data for other scripts (i.e. a deathscreen that displays killer name and how they killed you). Without this export, external scripts must listen to the native CEventNetworkEntityDamage and parse it on their own, which is very inefficient since Qbox is doing this already.
> 
> > 
> 
> > I think this is better as an export, rather than an event, but am definitely open to discussion if you think an event would be better. What is the benefit of using an event over an export for this?
> 
> 
> 
> How would this be used? The event makes sense to me so that other scripts can listen for an onDeath event if they care to take action when the player dies. Otherwise, they will have to call the export in a loop to continuously check.

I see where you're coming from. My scripts listen for changes to the client state bag instead of an event, so I only call the export when the state changes. I think this is good practice, but let me know if you disagree.

2024-07-22 16:11 UTC, Manason commented
> > > This is helpful for developers to be able to retrieve the killer's data for other scripts (i.e. a deathscreen that displays killer name and how they killed you). Without this export, external scripts must listen to the native CEventNetworkEntityDamage and parse it on their own, which is very inefficient since Qbox is doing this already.
> > 
> > 
> > > 
> > 
> > 
> > > I think this is better as an export, rather than an event, but am definitely open to discussion if you think an event would be better. What is the benefit of using an event over an export for this?
> > 
> > 
> > How would this be used? The event makes sense to me so that other scripts can listen for an onDeath event if they care to take action when the player dies. Otherwise, they will have to call the export in a loop to continuously check.
> 
> I see where you're coming from. My scripts listen for changes to the client state bag instead of an event, so I only call the export when the state changes. I think this is good practice, but let me know if you disagree.

Wouldn't it be more streamlined to have a named event with additional data (such as the killer data) rather than state bag listener + export?

2024-07-22 19:17 UTC, JHansen2000 commented
It would be more streamlined. I will update this tonight

2024-07-24 01:46 UTC, JHansen2000 commented
Sorry for the delay, this has been added simply as an event trigger. I do think this (and other events/exports) should be added to documentation somewhere but did not want to modify the README without approval.

2024-07-24 02:31 UTC, Manason requested changes

2024-07-24 02:31 UTC, Manason commented on client/dead.lua
> +    TriggerEvent('qbx_medical:client:attackerData', attacker, weapon)
Pass this data to the OnDeath function and to the existing onPlayerDied event. No need for a new event. https://github.com/Qbox-project/qbx_medical/blob/380465254d4af3f1c8c6d6e4c2f7ea0c3645647f/client/dead.lua#L26

2024-07-24 22:13 UTC, JHansen2000 commented
I passed the data as props to both OnDeath and StartLastStand and from there into the associated client & server events. It's all optional but is definitely very helpful. Hope that looks okay and this wasn't too much of a headache for you!

2024-07-25 05:44 UTC, Manason approved these changes

2024-07-25 05:45 UTC, merged